### ISSUE TITLE
Update README.rst

### ISSUE THREAD

**Issue by georgedouzas** [georgedouzas/sports-betting#5]
The README.rst is missing basic information.

**Comment by ItzBraveNoob** [comment]
Updated Readme.mst

**Comment by georgedouzas** [comment]
Hi @ItzBraveNoob,

Thanks for the PR. Please check the [documentation](https://sports-betting.readthedocs.io/en/latest/index.html) and add more information in the README.rst file.

**Comment by georgedouzas** [comment]
README.rst has been updated.
