### ISSUE TITLE
fixtures data were empty

### ISSUE THREAD

**Issue by popinskill** [georgedouzas/sports-betting#67]
Hi.. i tried everything coding but still: 
sportsbet dataloader fixtures -c turkey.py -d C:\Users\popinlinux\Desktop
┌──────────────────────────┐
│ Fixtures data were empty │

**Comment by georgedouzas** [comment]
Hi @popinskill,

Thanks, I will fix it asap.

**Comment by popinskill** [comment]
Can you give an example config can load the fixtures? Any league any div any year please

**Comment by georgedouzas** [comment]
@popinskill 

Can you check that latest version works as expected?
